### ISSUE TITLE
Builds fail due to http-builder dependency hosted by Bintray

### ISSUE THREAD

**Issue by KPrice725** [mopinion/mopinion-sdk-android-web#11]
Currently getting this build failure on our Android Project:

```
* What went wrong:
A problem occurred configuring root project '[secure]app'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.codehaus.groovy.modules.http-builder:http-builder:0.7.2.
     Required by:
         project :
      > Could not resolve org.codehaus.groovy.modules.http-builder:http-builder:0.7.2.
         > Could not get resource 'https://dl.bintray.com/mopinion/MopinionSDK/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom'.
            > Could not GET 'https://dl.bintray.com/mopinion/MopinionSDK/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom'. Received status code 502 from server: Bad Gateway
```

It seems like the Mopinion SDK has an external dependency on http-builder-0.7.2, which is hosted on Bintray.  The problem is Bintray was taken offline as of the end of October 2022.

**Comment by Piethot** [comment]
Hi @KPrice725, thanks for letting us know about this depreciated dependency. We will investigate this further and update you when we have more information.
Kind regards,
Pieter - Mopinion Support

**Comment by KPrice725** [comment]
Apologies, closing this issue, we just came across a bad declaration in our build.gradle file that was causing this issue.
