### ISSUE TITLE
Screenshot causes crash

### ISSUE THREAD

**Issue by saenic** [mopinion/mopinion-sdk-android-web#2]
I am an Android Developer trying to integrate the Web SDK in my app. When sending the "_button" event, the app crashes with a `TransactionTooLargeException`

The Web SDK always tries to send a screenshot when it calls `startFormWeb(true)`. There is a try catch block but this crash cannot be catched because it is thrown from Android System. 
It is caused because the Web SDK is trying to send an image as byte array stream in an Intent. This SHOULD NOT BE DONE because Intents are not made to handle large amounts of data and therefore crashing the app.

**Comment by stevenkuipers** [comment]
Hi @saenic, thanks for bringing this to our attention.

We are working on creating a solution to this issue. 
We aim to have an updated version, that addresses this solution within the coming two weeks.

**Comment by stevenkuipers** [comment]
Hi @saenic, 

This has been fixed in the latest version of this SDK (v0.1.7), together with [Crash on trigger #1](https://github.com/mopinion/mopinion-sdk-android-web/issues/1)
