### ISSUE TITLE
Actually place the source here on github

### ISSUE THREAD

**Issue by cristan** [mopinion/mopinion-sdk-android-web#3]
You have a github page, but this only contains a readme.md. Your SDK already open source (the source gets downloaded by Android studio automatically when I navigate to one of your classes), so let's post the source here.

**Comment by Piethot** [comment]
Hi Cristan,
Thanks for your suggestion. For now, we won't be placing the source on the page. If this will change in the future we will let you know.
Kind regards,
Pieter
