### ISSUE TITLE
Remove the NDK part of the instructions

### ISSUE THREAD

**Issue by cristan** [mopinion/mopinion-sdk-android-web#4]
Your documentation states that I should add this to my gradle file
```
ndk {
    abiFilters "armeabi", "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
}
```

This makes no sense: an SDK like this shouldn't need native code (and as far as I can tell, it doesn't have it). I didn't add this part and the SDK works just fine.

**Comment by Piethot** [comment]
Hi Cristan,

Thanks for your message. We will check your finding and provide you with an update as soon as we know more.

Kind regards,

Pieter

**Comment by Piethot** [comment]
This line of code was indeed a copy error in the instruction.

It’s needed for the react-native part of our mopinion-sdk-android. The mopinion-sdk-android-web however doesn’t contain react-native components so it doesn’t need it. We have removed the line from the instructions.

Kind regards,
Pieter
