### ISSUE TITLE
Migrate away from jCenter

### ISSUE THREAD

**Issue by vlazdra** [mopinion/mopinion-sdk-android-web#5]
Hi, since this library is being distributed via jCenter, you should do a migration in the next couple of months.
Official news here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Piethot** [comment]
Hi @vlazdra, thanks for letting us know. We will look into it and take required action. Kind regards, Pieter

**Comment by Piethot** [comment]
We will migrate in April. Thanks.
