### ISSUE TITLE
"Access to XMLHttpRequest at 'https://cacheorcheck.mopinion.com/survey/public/json-config?key=XXX&domain=XXX.mopinion.com&webView=true&withBase=true'    from origin 'XXX' has been blocked by has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Geertdepont** [mopinion/mopinion-sdk-android-web#6]
Hi there!

I have installed the mopinion web sdk for android, and the webview opens but the form is not loaded.
When I look at the logs I see that the request is blocked from the mopinion subdomain    https://XXX.mopinion.com.

No 'Access-Control-Allow-Origin' header is present on the requested resource.

We can try to intercept the request and attach the Access-Control-Allow-Origin, but this feels hacky.
How to solve this?

Best regards, Geert

**Comment by Piethot** [comment]
Hi Geert, Thanks for your comment. We look into this and get back to you as soon as possible.

**Comment by Piethot** [comment]
Hi Geert,

The problem you experienced has been solved. If you still experience otherwise please let us know. Kind regards, Pieter
