### ISSUE TITLE
Support AndroidX in stead of Android

### ISSUE THREAD

**Issue by welsinga** [mopinion/mopinion-sdk-android-web#7]
Seems this lightweight version isn't converted to use AndroidX in stead of Android. Please can you convert

**Comment by Piethot** [comment]
Thanks for letting us know. We will look into it. I will let you know when you can expect the conversion to AndroidX.

**Comment by Piethot** [comment]
@welsinga according to our developer all our SDKs are converted to AndroidX. This particular SDK is converted to AndroidX since version 0.2.0. He was wondering where you encountered Android instead of AndroidX. Can you highlight this for us? Kind regards, Pieter

**Comment by welsinga** [comment]
If you check with com.dipien.byebyejetifier (https://github.com/dipien/bye-bye-jetifier) you will discover you still have dependency with support classes like toolbar

**Comment by welsinga** [comment]
If you like I can sum-up the depending classes

**Comment by Piethot** [comment]
@welsinga we would be very grateful if you can sum up the depending classes.
