### ISSUE TITLE
Move aar outside Bintray and JCenter

### ISSUE THREAD

**Issue by welsinga** [mopinion/mopinion-sdk-android-web#8]
Bintray and Jcenter will stop working in Juni, please move aar to a different location, see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Piethot** [comment]
Thanks for letting us know. We will be moving the SDK to a different location before Bintray and Jcenter will stop working. We will update the documentation once this is done.

**Comment by Piethot** [comment]
Hi @welsinga, we have rehosted this SDK. Please see our updated documentation on how to get it. Thanks for your notice.
